# ===================================================================
#                      GENERIC CONFIGURATION
# ===================================================================
logging:
  level:
    # Use these for debugging SQL queries and their parameters
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

security:
  jwt:
    secret: OurPfeKey2019@@##'HpS
    expiration-ms: 3600000

# ===================================================================
#                     DATABASE CONFIGURATION
# ===================================================================
spring:
  datasource:
    #sqlite configuration ======================================
    # Using a dynamic filename based on the service name
    # url: jdbc:sqlite:${spring.application.name}.db
    # driver-class-name: org.sqlite.JDBC

    #oracle configuration ======================================
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: test_automation_user
    password: "1234"
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    #sqlite dialect ======================================
    # database-platform: org.hibernate.community.dialect.SQLiteDialect

    #oracle dialect ======================================
    database-platform: org.hibernate.dialect.Oracle12cDialect

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
