logging:
  level:
    com.hps.pfe: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

security:
  jwt:
    secret: OurPfeKey2019@@##'HpS
    expiration-ms: 3600000

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: test_automation_user
    password: "1234"
    driver-class-name: oracle.jdbc.OracleDriver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
