eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    # SQLite configuration (Edge Service)
    url: jdbc:sqlite:edge-service.db
    driver-class-name: org.sqlite.JDBC

    # Oracle configuration
    # url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    # username: test_automation_user
    # password: "1234"
    # driver-class-name: oracle.jdbc.OracleDriver

    # H2 configuration
    # url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=Oracle
    # driver-class-name: org.h2.Driver
    # username: sa
    # password:

  jpa:
    # use the community SQLite dialect if you added it above
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    secret: OurPfeKey2019@@##'HpS
    expiration-ms: 3600000
