# ===================================================================
#                      GENERIC CONFIGURATION
# ===================================================================
logging:
  level:
    # Use these for debugging SQL queries and their parameters
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

security:
  jwt:
    secret: OurPfeKey2019@@##'HpS
    expiration-ms: 3600000

# ===================================================================
#                     DATABASE CONFIGURATION
# -------------------------------------------------------------------
# This is the active configuration for all services.
# It uses a separate SQLite file for each service (e.g., corporate-management-service.db).
# ===================================================================
spring:
  datasource:
    # Using a dynamic filename based on the service name
    url: jdbc:sqlite:${spring.application.name}.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    # We use logging for SQL, so 'show-sql' is set to false to avoid duplicates.
    show-sql: false
