server:
  port: 8082

auth-service:
  wsdl-location: http://localhost:8083/ws/services/auth?wsdl
  namespace: http://hps.com/pfe/auth

corporate-service:
  wsdl-location: http://localhost:8084/ws/services/corporate?wsdl
  namespace: http://hps.com/pfe/corporate

client-service:
  wsdl-location: http://localhost:8085/ws/services/client?wsdl
  namespace: http://hps.com/pfe/client

spring:
  datasource:
    url: jdbc:sqlite:edge-service.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    gateway:
      routes:
        - id: auth-rest
          uri: lb://USER-AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: auth-soap
          uri: lb://USER-AUTH-SERVICE
          predicates:
            - Path=/ws/services/auth/**
          filters:
            - StripPrefix=3

        - id: corporate-rest
          uri: lb://CORPORATE-SERVICE
          predicates:
            - Path=/api/corporates/**
          filters:
            - StripPrefix=1

        - id: corporate-soap
          uri: lb://CORPORATE-SERVICE
          predicates:
            - Path=/ws/services/corporate/**
          filters:
            - StripPrefix=3

        - id: client-rest
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/api/clients/**
          filters:
            - StripPrefix=1

        - id: client-soap
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/ws/services/client/**
          filters:
            - StripPrefix=3

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui
