server:
  port: 8088
  servlet:
    context-path: /ws

cxf:
  path: /services

logging:
  level:
    com.hps.pfe: DEBUG
    org.flywaydb: INFO

spring:
  flyway:
    enabled: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
